# ============================================================
# CosmosDB-backed per-user chat session store
#
# CORE SERVICE — do not add domain-specific logic here.
# Each document is one conversation session, partitioned by user_id.
#
# Document schema:
# {
#     "id": "<session_id>",          -- unique, generated by frontend
#     "user_id": "<user_id>",        -- partition key (Entra oid or "anonymous")
#     "title": "...",                -- first message, truncated to 80 chars
#     "created_at": "ISO8601",
#     "updated_at": "ISO8601",
#     "message_count": int,
#     "messages": [
#         {
#             "id": "<uuid>",
#             "role": "user" | "assistant",
#             "content": "...",
#             "agent": "...",         -- agent that produced this response
#             "traces": [...],        -- handoff trace
#             "timestamp": "ISO8601"
#         }
#     ]
# }
# ============================================================

import logging
import uuid
from datetime import datetime, timezone

from azure.cosmos import PartitionKey, exceptions as cosmos_exceptions
from azure.cosmos.aio import CosmosClient

from app.config import Settings

logger = logging.getLogger(__name__)


class CosmosSessionStore:
    """
    Persists chat session documents (title + full message history) to Azure Cosmos DB.

    One document = one chat session.
    Partition key = user_id  (enables efficient per-user list queries).
    """

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._client: CosmosClient | None = None
        self._container = None

    async def initialize(self) -> None:
        """Connect to Cosmos DB and ensure the chat-sessions container exists."""
        from azure.identity.aio import DefaultAzureCredential

        credential = (
            self._settings.azure_cosmos_key
            if self._settings.azure_cosmos_key
            else DefaultAzureCredential(
                managed_identity_client_id=self._settings.azure_client_id or None
            )
        )

        self._client = CosmosClient(
            self._settings.azure_cosmos_endpoint,
            credential=credential,
        )

        db = self._client.get_database_client(self._settings.azure_cosmos_database_name)

        try:
            await db.create_container_if_not_exists(
                id=self._settings.azure_cosmos_sessions_container,
                partition_key=PartitionKey(path="/user_id"),
                default_ttl=7776000,  # 90 days
            )
        except Exception as exc:
            # Not fatal — container may already exist or RBAC may restrict listing
            logger.warning("Could not ensure chat-sessions container exists: %s", exc)

        self._container = db.get_container_client(
            self._settings.azure_cosmos_sessions_container
        )

    async def close(self) -> None:
        if self._client:
            await self._client.close()
            self._client = None

    # ------------------------------------------------------------------
    # Session lifecycle
    # ------------------------------------------------------------------

    async def create_session(
        self, session_id: str, user_id: str, title: str
    ) -> dict:
        """Create a new session document. Raises if session already exists."""
        now = datetime.now(timezone.utc).isoformat()
        doc = {
            "id": session_id,
            "user_id": user_id,
            "title": title,
            "created_at": now,
            "updated_at": now,
            "message_count": 0,
            "messages": [],
        }
        await self._container.create_item(body=doc)
        return doc

    async def get_session(self, session_id: str, user_id: str) -> dict | None:
        """Return the full session document (including messages), or None."""
        try:
            return await self._container.read_item(
                item=session_id, partition_key=user_id
            )
        except cosmos_exceptions.CosmosResourceNotFoundError:
            return None

    async def list_sessions(self, user_id: str) -> list[dict]:
        """Return lightweight session summaries (no messages) sorted newest-first."""
        query = (
            "SELECT c.id, c.user_id, c.title, c.created_at, c.updated_at, c.message_count "
            "FROM c WHERE c.user_id = @uid ORDER BY c.updated_at DESC"
        )
        items: list[dict] = []
        async for item in self._container.query_items(
            query=query,
            parameters=[{"name": "@uid", "value": user_id}],
            partition_key=user_id,
        ):
            items.append(item)
        return items

    async def delete_session(self, session_id: str, user_id: str) -> bool:
        """Delete a session. Returns True if deleted, False if not found."""
        try:
            await self._container.delete_item(
                item=session_id, partition_key=user_id
            )
            return True
        except cosmos_exceptions.CosmosResourceNotFoundError:
            return False

    # ------------------------------------------------------------------
    # Message persistence
    # ------------------------------------------------------------------

    async def append_message(
        self,
        session_id: str,
        user_id: str,
        role: str,
        content: str,
        agent: str | None = None,
        traces: list | None = None,
    ) -> None:
        """
        Append a message to an existing session using read-modify-write.

        If the session document does not exist (e.g. race condition at startup),
        the error is logged and silently swallowed so chat is never blocked.
        """
        now = datetime.now(timezone.utc).isoformat()
        message = {
            "id": str(uuid.uuid4()),
            "role": role,
            "content": content,
            "agent": agent,
            "traces": traces or [],
            "timestamp": now,
        }

        try:
            doc = await self._container.read_item(
                item=session_id, partition_key=user_id
            )
            doc["messages"].append(message)
            doc["message_count"] = len(doc["messages"])
            doc["updated_at"] = now
            await self._container.replace_item(item=session_id, body=doc)
        except cosmos_exceptions.CosmosResourceNotFoundError:
            logger.warning(
                "Session %s not found when appending message; skipping persistence.",
                session_id,
            )
        except Exception as exc:
            logger.error("Failed to append message to session %s: %s", session_id, exc)
